config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :bridezillas, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bridezilla.rb
class Bridezilla < ApplicationRecord
    has_many :guests
    has_secure_password
end

app/models/guest.rb
class Guest < ApplicationRecord
    belongs_to :bridezilla
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bridezillas_controller.rb
class BridezillasController < ApplicationController
  def new
    @bridezilla = Bridezilla.new
  end

  def create
    @bridezilla = Bridezilla.new(bride_params)
    if @bridezilla.save
      session[:user_id] = @bridezilla.id
      redirect_to guests_path
    else 
      render :new
    end
  end

  private 

  def bride_params
    params.require(:bridezilla).permit(:username, :password)
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    @guest = Guest.new
    
  end

  def create
    binding.pry
    @guest = Guest.create(guest_params)
    redirect_to guest_path(@guest)
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def index
    @guests = Guest.all
  end

  def edit
  end

  private 

  def guest_params
    params.require(:guest).permit(:name, :address)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bridezillas_helper.rb
module BridezillasHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/bridezillas/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@bridezilla) do |f| %>
    <%= f.text_field :username, placeholder: "username" %>
    <br>
    <%= f.password_field :password, placeholder: "password" %>
    <br>
    <%= f.submit "Sign Up" %>
<% end %>

app/views/guests/edit.html.erb
<h1>Guests#edit</h1>
<p>Find me in app/views/guests/edit.html.erb</p>

app/views/guests/index.html.erb
<h1>Guests</h1>
<ul><% @guests.each do |guest| %>
    <li><%= link_to guest.name, guest_path(guest) %></li>
<% end %></ul>

app/views/guests/new.html.erb
<h1>Add a Guest</h1>
<%= form_for(@guest) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.submit %>
<% end %>

<svg class="bi bi-battery-half" color="green" width="10em" height="10em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M12 5H2a1 1 0 00-1 1v4a1 1 0 001 1h10a1 1 0 001-1V6a1 1 0 00-1-1zM2 4a2 2 0 00-2 2v4a2 2 0 002 2h10a2 2 0 002-2V6a2 2 0 00-2-2H2z" clip-rule="evenodd"/>
  <path d="M2 6h5v4H2V6zm12.5 3.5a1.5 1.5 0 000-3v3z"/>
</svg>

<svg class="bi bi-heart-half" color="red" width="10em" height="10em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 1.314C3.562-3.248-7.534 4.735 8 15V1.314z" clip-rule="evenodd"/>
  <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 01.176-.17C12.72-3.042 23.333 4.867 8 15z" clip-rule="evenodd"/>
</svg>

app/views/guests/show.html.erb
<h1><%= @guest.name %></h1>
<ul>
    <li><%= @guest.email_address %></li>
    <li><%= @guest.address %></li>
    <li>Attending? <%= @guest.attending ? "Yes" : "No" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWedsAfternoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
  <nav class= "navbar-brand">
  <%= link_to "All guests", guests_path %>
  <%= link_to "Add a guest", new_guest_path %>
  </nav>
  </header>
  <body>
  <div class="space">
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </div>
    </body>
</html>